### PR TITLE
Updated the icon to the new Big Sur style

### PR DESCRIPTION
**Pull request by mickimnet**
Hello @yoannfleurydev, 

I followed Apple's Human Interface Guidelines for the App Icon and recreated the icon from scratch. Also I added the different PNG's in Xcode (as suggested by Apple).

- re-styled the icon in regards to the official Apple macOS Big Sur style guide
- created individual images with different content for all sizes

Take care
Mick

### CODE REVIEW

**Comment by mickimnet** [comment]
I did an embarrassing mistake, when I exported the PNGs from _Affinity Designer_ 😊🤦🏻 The last push fixed that.

**Comment by yoannfleurydev** [comment]
Thanks a lot for this update, this change was in my head for weeks now and I didn't took the time to do it.
I'll check this PR this week 👌🏻 

Thanks again for your contribution.

**Comment by mickimnet** [comment]
No hurry. You‘re very welcome. I love the tool!

**Comment by yoannfleurydev** [comment]
Thanks again, I'll release the dmg soon in the release section.

**Pull request merged**
